[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "droplet-vision"
dynamic = ["version"]
description = "Scientific interfaces for high-speed suspended-droplet vision"
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
cine = ["pims==0.7"]
ui = ["PySide6==6.10.2"]
release = ["PyInstaller==6.22.3"]

[tool.setuptools.dynamic]
version = {attr = "droplet_vision._version.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"droplet_vision.ui" = ["translations/*.json", "assets/icons/*.png", "assets/icons/*.ico"]
